# Generated by Django 5.0.1 on 2024-02-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_newletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewLetter',
            new_name='NewsLetter',
        ),
    ]
